language: java
jdk:
  - openjdk8

branches:
  only:
    - deploy

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

script: "./gradlew clean build"

before_deploy:
  - zip -r daymoji-springboot-webservice *
  - mkdir -p deploy
  - mv daymoji-springboot-webservice.zip deploy/daymoji-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo setting에 설정된 값
    bucket: daymoji-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "blossunn@gmail.com"
